openapi: 3.0.1

info:
  title: bff
  version: 0.0.1

servers:
  - url: http://localhost:3000
    description: local

tags:
  - name: Example

paths:
  /api/delay/{seconds}:
    get:
      operationId: getDelayString
      tags:
        - Example
      parameters:
        - in: path
          name: seconds
          required: true
          schema:
            type: integer
            format: int32
            description: delay
            example: 3
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'

components:
  schemas:
    ExampleResponse:
      type: object
      properties:
        firstResponse:
          type: string
        secondResponse:
          type: string
