/* tslint:disable */
/* eslint-disable */
/**
 * dummy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface GetDelayStringRequest {
    seconds: number;
}

/**
 * 
 */
export class DummyApi extends runtime.BaseAPI {

    /**
     */
    async getDelayStringRaw(requestParameters: GetDelayStringRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.seconds === null || requestParameters.seconds === undefined) {
            throw new runtime.RequiredError('seconds','Required parameter requestParameters.seconds was null or undefined when calling getDelayString.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/delay/{seconds}`.replace(`{${"seconds"}}`, encodeURIComponent(String(requestParameters.seconds))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async getDelayString(requestParameters: GetDelayStringRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getDelayStringRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
